(deftheme my
  "Created 2011-11-30. based on solarized-dark")

(custom-theme-set-faces
 'my
 '(default ((t (:stipple nil :background "#000505" :foreground "#708183" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "Consolas"))))
 '(cursor ((t (:background "#ff3311" :inverse-video t))))
 '(fringe ((t (:foreground "#465a61" :background "#111"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(minibuffer-prompt ((t (:foreground "#2075c7"))))
 '(highlight ((t (:background "#0a2832"))))
 '(region ((t (:background "#0a2832"))))
 '(shadow ((t (:foreground "grey70"))))
 '(secondary-selection ((t (:background "#0a2832"))))
 '(trailing-whitespace ((t (:background "#900"))))
 '(font-lock-builtin-face ((t (:foreground "#728a05"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "#465a61" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#465a61" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#259185"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "#259185" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#2075c7"))))
 '(font-lock-keyword-face ((t (:foreground "#728a05"))))
 '(font-lock-negation-char-face ((t (:foreground "#c60007"))))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face :foreground "#bd3612"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "#a57705"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "#bd3612"))))
 '(font-lock-string-face ((t (:foreground "#259185"))))
 '(font-lock-type-face ((t (:foreground "#a57705"))))
 '(font-lock-variable-name-face ((t (:foreground "#2075c7"))))
 '(font-lock-warning-face ((t (:inherit error :foreground "#c60007" :weight bold))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "#5859b7" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#c61b6e" :underline t))))
 '(header-line ((t (:inherit mode-line :background "#e9e2cb" :foreground "#708183" :box nil))))
 '(mode-line ((t (:box (:line-width 1 :color "#33ff33") :foreground "black" :background "#00b000"))))
 '(mode-line-buffer-id ((t (:background "black" :foreground "green" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width 1 :color "#00b000") :foreground "#00b000" :background "black"))))
 '(isearch ((t (:background "#b0b" :foreground "black"))))
 '(isearch-fail ((t (:background "red4"))))
 '(lazy-highlight ((t (:background "#413"))))
 '(match ((t (:background "RoyalBlue4"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit isearch))))
 '(senator-intangible-face ((t (:foreground "gray75"))))
 '(senator-momentary-highlight-face ((t (:background "gray13"))))
 '(senator-read-only-face ((t (:background "#664444"))))
 '(semantic-complete-inline-face ((t (:underline "yellow"))))
 '(semantic-decoration-on-fileless-includes ((t (:background "#005"))))
 '(semantic-decoration-on-includes ((t (:background "#030"))))
 '(semantic-decoration-on-private-members-face ((t (:background "#200000"))))
 '(semantic-decoration-on-protected-members-face ((t (:background "#000020"))))
 '(semantic-decoration-on-unknown-includes ((t (:background "#900000"))))
 '(semantic-decoration-on-unparsed-includes ((t (:background "#555500"))))
 '(semantic-highlight-edits-face ((t (:background "gray20"))))
 '(semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
 '(semantic-tag-boundary-face ((t (:overline "cyan"))))
 '(semantic-unmatched-syntax-face ((t (:underline "red"))))
 '(widget-button ((t (:weight bold))))
 '(widget-button-pressed ((t (:foreground "red1"))))
 '(widget-documentation ((t (:foreground "lime green"))))
 '(widget-field ((t (:box (:line-width 1 :color "#52676f") :foreground "gray" :background "dim gray"))))
 '(widget-inactive ((t (:inherit shadow))))
 '(widget-single-line-field ((t (:inherit widget-field))))
 '(custom-button ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "grey55"))))
 '(custom-button-mouse ((t (:foreground "white" :inherit custom-button))))
 '(custom-button-pressed ((t (:inherit custom-button-mouse :background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
 '(custom-button-pressed-unraised ((t (:inherit custom-button-unraised :foreground "violet"))))
 '(custom-button-unraised ((t (:inherit underline))))
 '(custom-changed ((t (:background "blue1" :foreground "white"))))
 '(custom-comment ((t (:background "dim gray" :foreground "gray"))))
 '(custom-comment-tag ((t (:background "#0a2832" :foreground "gray80"))))
 '(custom-documentation ((t (:inherit default))))
 '(custom-face-tag ((t (:inherit custom-variable-tag))))
 '(custom-group-tag ((t (:inherit variable-pitch :foreground "#bd3612" :weight bold :height 1.2))))
 '(custom-group-tag-1 ((t (:inherit variable-pitch :foreground "pink" :weight bold :height 1.2))))
 '(custom-invalid ((t (:background "red1" :foreground "yellow1"))))
 '(custom-link ((t (:inherit link :foreground "#5859b7"))))
 '(custom-modified ((t (:background "blue1" :foreground "white"))))
 '(custom-rogue ((t (:background "black" :foreground "pink"))))
 '(custom-saved ((t (:underline t))))
 '(custom-set ((t (:background "white" :foreground "blue1"))))
 '(custom-state ((t (:foreground "#728a05"))))
 '(custom-themed ((t (:background "blue1" :foreground "white"))))
 '(custom-variable-button ((t (:underline t :weight bold))))
 '(custom-variable-tag ((t (:foreground "#bd3612" :weight bold))))
 '(custom-visibility ((t (:inherit link :height 0.8))))
 '(hl-line ((t (:background "#080a0a")))))

(provide-theme 'my)
